---
title: 'Abstract'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

Throughout the world fisheries, commercial landings of sardine are known for strong year-to-year and multi-year variability. A key driver of this variability is thought to be environmental variability, to which small forage fish are especially sensitive. In this study, we study the landings fluctuations in the Indian oil sardine using a 32-year time series (1984-2015) with the goal of improving short-term (one year ahead) forecasts of landings. Past research on the oil sardine has examined a variety of environmental variables for their correlation with landings. In this study, we use that research along with knowledge of the annual life-cycle of the Indian oil sardine and critical periods for larval and juvenile survival and growth to develop a set of specific hypotheses concerning how oil sardine landings may relate to environmental variables in specific seasons. We focus on variables related to summer upwelling timing and intensity, sea temperature and multi-year indices of ocean condition. We use generalized additive models (GAMs) with past landings and environmental covariates as the predictors in order to study the relationship between predictors and future landings. GAMs allow flexible non-linear effect curves, which is important since prior research on sardines and environmental variables as demonstrated threshold responses and critical variable windows. For many of the hypothesized drivers of landings fluctuations, we found no correlation between the variable and either monsoon or post-monsoon landings. Precipitation, whether the amount or timing, has often been proposed as a predictor of oil sardine landings, however we found no correlation between precipitation in spring, summer or fall with either monsoon or post-monsoon landings. Similarly, we found no correlations between sea-surface temperature (SST) during spring or fall. We also found no correlation between landings and 9-12 month lagged measures of the El Nino/Southern Oscillation (ENSO).  Instead, we found significant correlation for two variables: upwelling intensity and long-term average SST.  We found significant correlation between landings, both monsoon and post-monsoon, and the current year upwelling intensity in June-September either as measured by the nearshore-offshore SST gradient or average nearshore SST. Upwelling intensity is related both to a positive effect (higher food availability for sardines during late summer and fall) but also to a negative effect at extreme intensity (poorly oxygenated water extending to the sea surface). Thus a correlation between upwelling intensity and landings is not surprising. However, the most significant correlation we found was between the 2.5 year average nearshore SST and post-monsoon landings. A model with this covariate had an adjusted R2 of 67.5 versus 56.6 for the model with only prior landings and no environmental covariates. The SST averaged over multiple years has also been found to be a significant predictor for Pacific sardines and southern African sardines. This suggests that for sardines, the average SST over the sardine life-span successfully captures a variety of factors which predict future abundance. The temperature of the Western Indian Ocean has been at a rate higher than other tropical oceans and the warming has been most extreme during the summer monsoon months. Our work highlights that changes in upwelling intensity and sea temperature are likely to impact landings and should be included forecasting models. 
