---
title: "Generic set-up for all Rmds"
author: "EE Holmes"
output: html_document
---

```{r message=FALSE,warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(SardineForecast)
library(stringr)
library(mgcv)
library(knitr)
# If this is being called from another Rmd (as a child), this counter will exist
if(!exists(".rmdenvir")) .rmdenvir = environment()
#detect if making latex
knitOut=knitr::opts_knit$get("rmarkdown.pandoc.to")
if(length(knitOut)==0) isLatex=FALSE else isLatex=(knitOut=="latex")
```


```{r message=FALSE,warning=FALSE, echo=FALSE}
Qtr=3 # start of season
reg="Kerala"
respdat=data.frame(
  spawners0=oilsardine_qtr[[reg]][oilsardine_qtr$Qtr==3]
  )
catch0=filter(oilsardine_qtr[[reg]],c(1,1,1,1),sides=1)[seq(6,dim(oilsardine_qtr)[1],4)]
respdat$Catch0 = c(catch0,NA)
CatchWin=filter(oilsardine_qtr[[reg]],c(0,1,1,0),sides=1)[seq(6,dim(oilsardine_qtr)[1],4)]
respdat$CatchWin0 = c(CatchWin,NA)
CatchSum=filter(oilsardine_qtr[[reg]],c(1,0,0,1),sides=1)[seq(6,dim(oilsardine_qtr)[1],4)]
respdat$CatchSum0 = c(CatchSum,NA)

#add Catch - spawners
respdat$nspawners0 = respdat$Catch0 - respdat$spawners0
respdat$nspawners0 = respdat$CatchWin0

respdat=log(respdat)

  covnames=c(
    "log.CHL.4","log.CHL.5",
    "log.CHL.4","log.CHL.5",
    "log.CHL.4","log.CHL.5",
    "SST.UPW.5","SST.UPW.4",
    "SST.UPW.5","SST.UPW.4",
    "SST.UPW.5","SST.UPW.4",
    "SST.UPW.5","SST.UPW.4",
    "SST.5","SST.4",
    "SST.5","SST.4",
     "SST.2","SST.3","SST.4","SST.5",
    "SST.7","SST.8","SST.9","SST.10",
    "SST.2","SST.3","SST.4","SST.5",
    "SST.7","SST.8","SST.9","SST.10",
    "SST.2","SST.3","SST.4","SST.5",
    "SST.7","SST.8","SST.9","SST.10",
    "SST.2","SST.3","SST.4","SST.5",
    "SST.7","SST.8","SST.9","SST.10",
    "SST.2","SST.3","SST.4","SST.5",
    "SST.7","SST.8","SST.9","SST.10",
    "SST.11","SST.12","SST.13",
    "SST.11","SST.12","SST.13",
    "SST.11","SST.12","SST.13",
    "SST.11","SST.12","SST.13",
    "SST.11","SST.12","SST.13",
   "precip.gpcp.kerala", "precip.gpcp.kerala")
  covmon=list(
     7:9,7:9,
     1:3,1:3,
     10:12,10:12,
     6:9,6:9,
     1:3,1:3,
     4:6,4:6,
     10:12,10:12,
     1:3,1:3,
     1:12,1:12,
     6:9,6:9,6:9,6:9,
     6:9,6:9,6:9,6:9,
     9:10,9:10,9:10,9:10,
     9:10,9:10,9:10,9:10,
     1:12,1:12,1:12,1:12,
     1:12,1:12,1:12,1:12,
     3:5,3:5,3:5,3:5,
     3:5,3:5,3:5,3:5,
     10:12,10:12,10:12,10:12,
     10:12,10:12,10:12,10:12,
     9:10,9:10,9:10,
     1:12,1:12,1:12,
     1:5,1:5,1:5,
     6:9,6:9,6:9,
     10:12,10:12,10:12,
     4:5,6:7)

#fix problem in seio_covariates_mon with SST in 1994.
  #replace with 5 year mean for that month
  seio_covariates_mon2 = seio_covariates_mon
  tmpcov=c("SST.UPW.3","SST.UPW.4","SST.UPW.5","SST.2",
           "SST.3","SST.4","SST.5","SST.7","SST.8","SST.9","SST.10","SST.11","SST.12","SST.13")
  for(itmpcov in tmpcov){
    for(mon in 10:12){
    filt1=with(seio_covariates_mon2, Year==1994 & Month==mon)
    if(!is.na(seio_covariates_mon2[filt1,itmpcov])) next
    filt2=with(seio_covariates_mon2, Year%in%(1990:1996) & Month==mon)
    seio_covariates_mon2[filt1,itmpcov]=mean(seio_covariates_mon[filt2,itmpcov], na.rm=TRUE)
    }
  }
     
n=2 #max lag in cov to use
for(i in 1:length(covnames)){
  covname=covnames[i]
  mon=covmon[[i]]
  varname=paste(covname,".mon",mon[1],"to",mon[length(mon)],".0",sep="")
  covdat=tapply(seio_covariates_mon2[[covname]],seio_covariates_mon2$Year,function(x){mean(x[mon],na.rm=TRUE)})
  covdat[is.infinite(covdat)]=NA
  maxcovdat=tapply(seio_covariates_mon2[[covname]],seio_covariates_mon2$Year,function(x){max(x[mon],na.rm=TRUE)})
  maxcovdat[is.infinite(covdat)]=NA  
  if(str_detect(varname, "mon1to3")|str_detect(varname, "mon4to6")){
    respdat[[varname]]=c(covdat[-1],NA)
    respdat[[paste0("max.",varname)]]=c(maxcovdat[-1],NA)
 }else{
    respdat[[varname]]=covdat
    respdat[[paste0("max.",varname)]]=maxcovdat
  }
}
for(j in c("mon9to10.0", "mon6to9.0", "mon1to12.0", "mon3to5.0",  "mon10to12.0")){
  varname=paste0("SST.",c(2:5),".",j)
  tmp=apply(respdat[,varname],1,mean,na.rm=TRUE)
  varname=paste0("SST.2.10.",j)
  respdat[[varname]]=tmp
}

#add lags
for(i in colnames(respdat)){
  name=paste(str_sub(i, 1, str_length(i)-1),"1",sep="")
  respdat[[name]]=c(NA,respdat[[i]][1:(dim(respdat)[1]-1)])
  name=paste(str_sub(i, 1, str_length(i)-1),"2",sep="")
  respdat[[name]] = c(NA,NA,respdat[[i]][1:(dim(respdat)[1]-2)])
}
respdat$Year=oilsardine_qtr$Year[oilsardine_qtr$Qtr==Qtr]

fullrespdat = respdat
```

```{r message=FALSE,warning=FALSE, echo=FALSE}
covnames = c("precip.gpcp.kerala.mon6to7.", "precip.gpcp.kerala.mon4to5.", 
             "SST.4.mon1to12.", "SST.4.mon6to9.", 
             "SST.UPW.4.mon1to3.", "SST.UPW.4.mon6to9.", "SST.UPW.4.mon10to12.", "SST.UPW.4.mon4to6.",
             "max.SST.UPW.4.mon6to9.",
             "SST.2.10.mon6to9.", "SST.2.10.mon9to10.", "SST.2.10.mon1to12.",
             "SST.2.10.mon3to5.", "SST.2.10.mon10to12.")
#set up to use consistent data
dat=fullrespdat[,c("Year","spawners0", "nspawners1", "spawners0", "spawners1", "spawners2", paste(covnames, "0", sep=""), paste(covnames, "1", sep=""))]
dat=na.omit(dat)
dat.spawners=dat
if(any(diff(dat.spawners$Year)!=1)) stop("Problem in setup.Rmd.  The covariate data.frame cannot have any missing years.")
```

```{r message=FALSE,warning=FALSE, echo=FALSE}
covnames = c("precip.gpcp.kerala.mon6to7.", "precip.gpcp.kerala.mon4to5.", 
             "SST.4.mon1to12.", "SST.4.mon6to9.", 
             "SST.UPW.4.mon1to3.", "SST.UPW.4.mon6to9.", "SST.UPW.4.mon10to12.", "SST.UPW.4.mon4to6.",
             "max.SST.UPW.4.mon6to9.",
             "SST.2.10.mon6to9.", "SST.2.10.mon9to10.", "SST.2.10.mon1to12.", 
             "SST.2.10.mon3to5.", "SST.2.10.mon10to12.")
#set up to use consistent data
dat=fullrespdat[,c("Year","nspawners0", "nspawners1", "spawners0", "spawners1", "spawners2", paste(covnames, "0", sep=""), paste(covnames, "1", sep=""))]
dat=na.omit(dat)
dat.nonspawners=dat
if(any(diff(dat.nonspawners$Year)!=1))
  stop("Problem in setup.Rmd.  The covariate data.frame cannot have any missing years.")
rm(dat) #make sure I don't accidentally forget to define dat

dat=fullrespdat[,c("Year","nspawners0", "nspawners1", "spawners0", "spawners1", "spawners2", paste(covnames, "0", sep=""), paste(covnames, "1", sep=""))]
dat.nonspawners.nocov=dat[dat$Year<2015,]
rm(dat) #make sure I don't accidentally forget to define dat
```

```{r message=FALSE,warning=FALSE, echo=FALSE}
covnames = c("log.CHL.4.mon1to3.", "log.CHL.4.mon7to9.", "log.CHL.4.mon10to12.",
             "log.CHL.5.mon1to3.", "log.CHL.5.mon7to9.", "log.CHL.5.mon10to12.",
             "precip.gpcp.kerala.mon6to7.", "precip.gpcp.kerala.mon4to5.",
             "SST.4.mon1to12.", "SST.4.mon6to9.", 
             "SST.UPW.4.mon1to3.", "SST.UPW.4.mon6to9.", "SST.UPW.4.mon10to12.", "SST.UPW.4.mon4to6.",
             "max.SST.UPW.4.mon6to9.",
             "SST.2.10.mon6to9.", "SST.2.10.mon9to10.", "SST.2.10.mon1to12.",
             "SST.2.10.mon3to5.", "SST.2.10.mon10to12.")
#set up to use consistent data
dat=fullrespdat[,c("Year", "spawners0", "nspawners0",
                   "nspawners1", "spawners2",
                   "CatchWin0", "CatchWin1", "CatchWin2",
                   paste(covnames, "0", sep=""), paste(covnames, "1", sep=""))]
dat=na.omit(dat)
dat.chl=dat
if(any(diff(dat.chl$Year)!=1))
  stop("Problem in setup.Rmd.  The covariate data.frame cannot have any missing years.")
rm(dat) #make sure I don't accidentally forget to define dat
```
