---
title: "Spawner Covariates Analysis (Catch in Qtr 3)"
author: "EE Holmes"
date: "October 20, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
require(SardineForecast)
require(stringr)
require(mgcv)
require(knitr)
```

```{r setup-data, echo=FALSE}
reg="Kerala"
    respdat=data.frame(
      spawners0=oilsardine_qtr[[reg]][oilsardine_qtr$Qtr==3]
      )
    catch0=filter(oilsardine_qtr[[reg]],c(1,1,1,1),sides=1)[seq(6,dim(oilsardine_qtr)[1],4)]
    respdat$Catch0 = c(catch0,NA)
    respdat=log(respdat)
    
  covnames=c(
    "log.CHL.3","log.CHL.4","log.CHL.5",
    "log.CHL.3","log.CHL.4","log.CHL.5",
    "log.CHL.3","log.CHL.4","log.CHL.5",
    "SST.UPW.3","SST.UPW.4","SST.UPW.5",
    "SST.UPW.3","SST.UPW.4","SST.UPW.5",
    "SST.UPW.3","SST.UPW.4","SST.UPW.5",
    "SST.3","SST.4","SST.5",
    "SST.3","SST.4","SST.5",
    "SST.3","SST.4","SST.5",
    "precip.gpcp.kerala", "precip.gpcp.kerala")
  covmon=list(
     7:9,7:9,7:9,
     1:3,1:3,1:3,
     10:12,10:12,10:12,
     7:9,7:9,7:9,
     1:3,1:3,1:3,
     10:12,10:12,10:12,
     7:12,7:12,7:12,
     1:3,1:3,1:3,
     10:12,10:12,10:12,
     4:5,6:7)
  n=2 #max lag in cov to use
  for(i in 1:length(covnames)){
    covname=covnames[i]
    mon=covmon[[i]]
      varname=paste(covname,".mon",mon[1],"to",mon[length(mon)],".0",sep="")
      covdat=tapply(seio_covariates_mon[[covname]],seio_covariates_mon$Year,function(x){mean(x[mon],na.rm=TRUE)})
      respdat[[varname]]=covdat
  }
  #add lags
  for(i in colnames(respdat)){
    name=paste(str_sub(i, 1, str_length(i)-1),"1",sep="")
    respdat[[name]]=c(NA,respdat[[i]][1:(dim(respdat)[1]-1)])
    name=paste(str_sub(i, 1, str_length(i)-1),"2",sep="")
    respdat[[name]] = c(NA,NA,respdat[[i]][1:(dim(respdat)[1]-2)])
  }
  respdat$Year=oilsardine_qtr$Year[oilsardine_qtr$Qtr==3]
  #add Catch - spawners
  respdat$nspawners0 = respdat$Catch0 - respdat$spawners0
  respdat$nspawners1 = respdat$Catch1 - respdat$spawners1
  respdat$nspawners2 = respdat$Catch2 - respdat$spawners2

fullrespdat=respdat
```


```{r seltable, echo=FALSE}
respdat = fullrespdat[which(fullrespdat$Year==1983):which(fullrespdat$Year==2015),]

#set up table
seltable = data.frame(Model="&nbsp;", Residual.df="&nbsp;", Residual.dev="&nbsp;", F="&nbsp;", p.value="&nbsp;", AIC="&nbsp;", stringsAsFactors=FALSE)

for(covname in c("precip.gpcp.kerala.mon6to7.", "precip.gpcp.kerala.mon4to5.", 
                 "SST.4.mon7to12.",
                 "SST.UPW.4.mon1to3.", "SST.UPW.4.mon7to9.", "SST.UPW.4.mon10to12.")){
#set up table
  if(covname=="precip.gpcp.kerala.mon6to7.") covtit = "Jun-Jul Precipitation"
  if(covname=="precip.gpcp.kerala.mon4to5.") covtit = "Apr-May Precipitation"
  if(covname=="SST.4.mon10to12.") covtit = "Oct-Dec SST"
  if(covname=="SST.4.mon7to12.") covtit =  "Jul-Dec SST"
  if(covname=="SST.4.mon1to3.") covtit =  "Jan-Mar SST"
  if(covname=="SST.UPW.4.mon10to12.") covtit = "Oct-Dec Upwelling"
  if(covname=="SST.UPW.4.mon7to9.") covtit = "Jul-Aug Upwelling"
  if(covname=="SST.UPW.4.mon1to3.") covtit = "Jan-Mar Upwelling"

seltable = rbind(seltable, data.frame(Model=covtit, Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors=FALSE))

#Precipitation during monsoon
dat=fullrespdat[which(fullrespdat$Year==1983):which(fullrespdat$Year==2015),c("spawners0", "Catch1", paste(covname, "0", sep=""), paste(covname, "1", sep=""))]
dat=na.omit(dat)
dat$cov0=dat[[paste(covname, "0", sep="")]]
dat$cov1=dat[[paste(covname, "1", sep="")]]
#dat$cov2=dat[[paste(covname, "2", sep="")]]
m1 = gam(spawners0 ~ s(Catch1, sp=0.6), data=dat)
m2 = gam(spawners0 ~ s(Catch1, sp=0.6) + cov0, data=dat)
m3 = gam(spawners0 ~ s(Catch1, sp=0.6) + s(cov0, sp=0.6), data=dat)
m4 = gam(spawners0 ~ s(Catch1, sp=0.6) + s(cov0, sp=0.6) + cov1, data=dat)
m5 = gam(spawners0 ~ s(Catch1, sp=0.6) + s(cov0, sp=0.6) + s(cov1, sp=0.6), data=dat)
m6 = gam(spawners0 ~ s(Catch1, cov0, sp=0.6), data=dat)
a=anova(m1,m2,m3,m4,m5, test="F")

#model 1
i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="$ln(S_t)$ = $\\alpha$ + $s(ln(N_{t-1}))$ + $\\epsilon$",
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F="", p.value="", AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "%, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="$ln(S_t)$ = $\\alpha$ + $s(ln(N_{t-1}))$ + $\\beta V_t$ + $\\epsilon$",
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), AIC = round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "%, Var($\\epsilon$) = ", round(m3$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value = "", AIC= "")
seltable=rbind(seltable,tmp1,tmp2)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="$ln(S_t)$ = $\\alpha$ + $s(ln(N_{t-1}))$ + $s(V_t)$ + $\\epsilon$",
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), AIC = round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "%, Var($\\epsilon$) = ", round(m3$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value = "", AIC= "")
seltable=rbind(seltable,tmp1,tmp2)

#model 4
i=4; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="$ln(S_t)$ = $\\alpha$ + $s(ln(N_{t-1}))$ + $s(V_t)$ + $V_{t-1}$ + $\\epsilon$", 
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), AIC = round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "%, Var($\\epsilon$) = ", round(m3$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value = "", AIC= "")
seltable=rbind(seltable,tmp1,tmp2)

#model 5
i=5; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="$ln(S_t)$ = $\\alpha$ + $s(ln(N_{t-1}))$ + $s(V_t)$ + $s(V_{t-1})$ + $\\epsilon$", 
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), AIC = round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "%, Var($\\epsilon$) = ", round(m3$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value = "", AIC= "")
seltable=rbind(seltable,tmp1,tmp2)

## Space
tmp1 = data.frame(Model="&nbsp;", Residual.df="&nbsp;", Residual.dev="&nbsp;", F="&nbsp;", p.value="&nbsp;", AIC="")
seltable=rbind(seltable,tmp1)

#######################################################################
}
```

```{r print-table, echo=FALSE}
colnames(seltable)=c("Model", "Residual df", "Residual deviance", "F", "p value", "AIC")
kable(seltable, align="lccccc")
```
