---
title: 'Supplemental Information: Full model tests and diagnostics'
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = 'setup.Rmd'}
```

```{r echo=FALSE}
Supplement <- TRUE # Change if this will be labelled appendix
if(!exists(".rmdenvir")) .rmdenvir = environment()
# here::set_here()
```

# Tests for prior season catch as covariate

```{r child = file.path('SupplementFiles', 'Table App A spawner model.Rmd')}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

```{r child = file.path('SupplementFiles', 'Table App A nonspawner model.Rmd')}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

# Tests for environmental variables as covariates

```{r child = file.path('SupplementFiles', 'Table App B spawner covariates.Rmd'), eval=FALSE}
```

```{r, results="asis", echo=FALSE, eval=FALSE}
cat("\\clearpage")
```

```{r child = file.path('SupplementFiles', 'Table App B nonspawner covariates M with S2.Rmd'), eval=FALSE}
```

```{r, results="asis", echo=FALSE, eval=FALSE}
cat("\\clearpage")
```

```{r child = file.path('SupplementFiles', 'Table App B nonspawner covariates M wo S2.Rmd'), eval=FALSE}
```

```{r child = file.path('AppendixFiles', 'AppendixNonSpawner.Rmd')}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

<!--
# Tests for Chlorophyll-a as a covariate
-->

```{r child = file.path('SupplementFiles', 'Table App C chlorophyll.Rmd'), eval=FALSE}
```

```{r, results="asis", echo=FALSE, eval=FALSE}
cat("\\clearpage")
```


# Validation of catch base models

```{r child = file.path('SupplementFiles', 'Table App D.Rmd')}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

# Comparison of land and oceanic rainfall measurements

```{r echo=FALSE}
#set the table pre
if(Supplement){
  pre <- "S"
  figset <- "figsupp:"
}else{
  pre <- "E"
  figset <- "figappE:"
}
```

```{r echo=FALSE}
thecap=paste0("Monthly precipitation measured over land via land gauges versus the precipitation measured via remote sensing over the ocean.")
fullcap.precip <- paste0("Figure ", ref(paste0(figset,"figprecip"), pre=pre), ". ", thecap)
```

```{r rainfall.mon.comparison, echo=FALSE,fig.cap=fullcap.precip, fig.width=6,fig.height=6,message=FALSE,warning=FALSE}
plot(seio_covariates_mon$Precip.Kerala, seio_covariates_mon$precip.gpcp.kerala, ylab="Monthly land precipitation (mm)",
xlab="Monthly ocean precipitation (average mm/day)")
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

# Comparison of multiyear average regional SST and DMI

```{r echo=FALSE}
thecap=paste0("Multiyear average regional SST versus multiyear average DMI. Adjusted $R^2$=40.9%")
fullcap.dmi <- paste0("Figure ", ref(paste0(figset,"figsstvdmi"), pre=pre), ". ", thecap)
```

```{r sst.dmi.comparison, echo=FALSE,fig.cap=fullcap.dmi, fig.width=6,fig.height=6,message=FALSE,warning=FALSE}
plot(fullrespdat$DMI.3.yr.runsum.0, fullrespdat$SST.2.10.3.yr.runsum.0, xlab="2.5-year average DMI", ylab="2.5-year average regional SST")
```

