---
title: 'Table 2: Post-Monsson Model Selection'
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = 'setup.Rmd'}
```



```{r seltable2, echo=FALSE}
#dat.spawners defined in setup-covariates.Rmd
dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)

#respdat = fullrespdat[which(fullrespdat$Year==Yr1):which(fullrespdat$Year==Yr2),]
respdat = dat
#naive model error
NE=mean(abs(respdat$nspawners0-respdat$nspawners1))

#set up table
seltable = data.frame(
  Model=paste("Naive Model ", min(respdat$Year),"-", max(respdat$Year), " data", sep=""), 
  Residual.df="", 
  MASE="",
  Adj.R2="", F="", 
  p.value="", 
  AIC="", stringsAsFactors=FALSE)

mne = lm(nspawners0 ~ -1 + offset(nspawners1), data=respdat)

#naive model
mod="mne"
aa = summary(get(mod))
tmp1=data.frame(
  Model="$ln(N_t)$ = $ln(N_{t-1})$ + $\\epsilon_t$", 
  Residual.df=round(aa$df[2],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2="", 
  F="", 
  p.value="", 
  AIC=round(AIC(get(mod)), digits=2)
  )
seltable=rbind(seltable,tmp1)

## Space
tmp1 = data.frame(
  Model="\\kern 1em", 
  Residual.df="\\kern 1em", 
  MASE="\\kern 1em", 
  Adj.R2="",
  F="\\kern 1em",
  p.value="\\kern 1em", 
  AIC="", stringsAsFactors=FALSE)
tmp2 = data.frame(
  Model="Time dependency test", 
  Residual.df="", 
  MASE="",
  Adj.R2="", F="", p.value="", AIC="", stringsAsFactors=FALSE)
seltable=rbind(seltable,tmp1,tmp2)

#5 is most complex
m0 = gam(nspawners0 ~ nspawners1 + nspawners2 + spawners1 + spawners2, data=respdat)
m1 = gam(nspawners0 ~ spawners1, data=m0$model)
m2 = gam(nspawners0 ~ nspawners1, data=m0$model)

i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="1. $ln(N_t)$ = $\\alpha$ + $\\beta ln(S_{t-1})$ + $\\epsilon_t$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F="", 
  p.value="", 
  AIC=round(AIC(get(mod)), digits=2)
  )
seltable=rbind(seltable,tmp1)

i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(N_t)$ = $\\alpha$ + $\\beta ln(N_{t-1})$ + $\\epsilon_t$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F="", 
  p.value="", 
  AIC=round(AIC(get(mod)), digits=2)
  )
seltable=rbind(seltable,tmp1)

## Space
tmp1 = data.frame(
  Model="\\kern 1em", 
  Residual.df="\\kern 1em", 
  MASE="\\kern 1em", 
  Adj.R2="",
  F="\\kern 1em",
  p.value="\\kern 1em", 
  AIC="", stringsAsFactors=FALSE)
tmp2 = data.frame(
  Model="Linearity and time-dependency test", 
  Residual.df="", 
  MASE="",
  Adj.R2="", F="", p.value="", AIC="", stringsAsFactors=FALSE)
seltable=rbind(seltable,tmp1,tmp2)

#5 is most complex
m5 = gam(nspawners0 ~ nspawners1+nspawners2+spawners2, data=respdat)
m0=m5
m1 = gam(nspawners0 ~ nspawners1, data=m0$model)
m2 = gam(nspawners0 ~ s(nspawners1, sp=0.6), data=m0$model)
m3 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(nspawners2, sp=0.6), data=m0$model)
m4 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=m0$model)
a=anova(m1,m2,m3,m4, test="F")

#linear on N1
i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="1. $ln(N_t)$ = $\\alpha$ + $\\beta ln(N_{t-1})$ + $\\epsilon_t$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=2), 
  F="", p.value="", 
  AIC=round(AIC(get(mod)), digits=2), stringsAsFactors=FALSE)
seltable=rbind(seltable, tmp1)

#linear ln N_t
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(N_t)$ = $\\alpha$ + $s(ln(N_{t-1}))$ + $\\epsilon_t$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=2), 
  F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), 
  AIC=round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#linear ln Catch1 + ln Catch2
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3a. $ln(N_t)$ = $\\alpha$ + $s_1(ln(N_{t-1}))$ + $s_2(ln(N_{t-2}))$ + $\\epsilon_t$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=2), 
  F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), 
  AIC=round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#linear ln N1 + ln S2
i=4; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3b. $ln(N_t)$ = $\\alpha$ + $s_1(ln(N_{t-1}))$ + $s_2(ln(S_{t-2}))$ + $\\epsilon_t$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=2), 
  F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), 
  AIC=round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)
```


```{r print-table2, echo=FALSE}
colnames(seltable)=c("Model", "Residual df", "MASE", "Adj.R2", "F", "p value", "AIC")
if(isLatex) colnames(seltable)=c("Model", "\\shortstack{Residual\\\\df}", "MASE", "\\shortstack{Adj.\\\\R2}", "F", "\\shortstack{p\\\\value}", "AIC")

thecap=paste("Model selection tests for the post-monsoon (Oct-Mar) catch model ($N_t$) using F-tests and AIC.  $S_t$ is the catch during the monsoon (Jul-Sep). $N_t$ is the catch during the post-monsoon period (Oct-Mar) of season $t$; note the fishing season is defined as Jul-Jun not calendar year. $S_{t-1}$ and $N_{t-1}$ are the catch during the prior sardine season during and after the monsoon respectively. $S_{t-2}$ and $N_{t-2}$ are the same for two seasons prior. ")
fullcap=paste("Table ", ref("tab:nonspawner-models"), ". ", thecap, sep="")
kable(seltable, align="lcccccc", caption=fullcap, escape=FALSE)
```