---
title: 'Table 3: Non-Spawner Model Selection'
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = 'setup.Rmd'}
```

```{r table3-cov-models}
dat=dat.spawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon1to3.1")
covtits =  c("Jul-Sep SST current season", "Jan-Mar UPW prior season")
dat$cov0=dat[[covnames[1]]]
dat$cov1=dat[[covnames[2]]]
m1 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov1, sp=0.6), data=dat)

dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon10to12.1")
covtits =  c("Jul-Sep SST current season", "Oct-Dec UPW prior season")
dat$cov0=dat[["SST.4.mon7to9.0"]]
dat$cov1=dat[["SST.UPW.4.mon10to12.1"]]
m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov1, sp=0.6), data=dat)
```

```{r seltable3, echo=FALSE}
dat=dat.spawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon1to3.1")
covtits =  c("Jul-Sep SST current season", "Jan-Mar UPW prior season")
dat$cov0=dat[["SST.4.mon7to9.0"]]
dat$cov1=dat[["SST.UPW.4.mon1to3.1"]]
m1 = gam(spawners0 ~ s(nspawners1, sp=0.6), data=dat)
m2 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov0, sp=0.6), data=dat)
m3 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov0, sp=0.6) + s(cov1, sp=0.6), data=dat)
a=anova(m1,m2,m3, test="F")

## Header
tmp1 = data.frame(Model="Jul-Sep catch models with covariates", Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors = FALSE)
tmp2 = data.frame(Model="$V_t$ = Jul-Sep SST current season", Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors = FALSE)
tmp3 = data.frame(Model="$W_{t-1}$ = Jan-Mar upwelling prior season", Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors = FALSE)
seltable=rbind(tmp1,tmp2,tmp3)

i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="I-M0: $ln(S_t) = \\alpha + s(ln(N_{t-1})) + \\epsilon$", Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F="", p.value="", AIC=round(AIC(get(mod)), digits=2), stringsAsFactors=FALSE)
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="II: $ln(S_t) = M0 + s(V_t)$", 
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="III: $ln(S_t) = M0 + s(V_t) + s(W_{t-1})$", Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

m1 = gam(spawners0 ~ s(nspawners1, sp=0.6), data=dat)
m2 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov1, sp=0.6), data=dat)
a=anova(m1,m2, test="F")

i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="II: $ln(S_t) = M0 + s(W_{t-1})$", Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

## Space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", Residual.dev="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="", stringsAsFactors = FALSE)
seltable=rbind(seltable,tmp1)

dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon10to12.1")
covtits =  c("Jul-Sep SST current season", "Oct-Dec UPW prior season")
dat$cov0=dat[["SST.4.mon7to9.0"]]
dat$cov1=dat[["SST.UPW.4.mon10to12.1"]]
m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=dat)
m2 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
m3 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6) + cov1, data=dat)
a=anova(m1,m2,m3, test="F")

## Header
tmp1 = data.frame(Model="Oct-Jun catch models with covariates", Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors = FALSE)
tmp2 = data.frame(Model="$V_t$ = Jul-Sep SST current season", Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors = FALSE)
tmp3 = data.frame(Model="$W_{t-1}$ = Oct-Dec upwelling prior season", Residual.df="", Residual.dev="", F="", p.value="", AIC="", stringsAsFactors = FALSE)
seltable=rbind(seltable,tmp1,tmp2,tmp3)

i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="I-M1: $ln(N_t) = \\alpha + s(ln(N_{t-1})) + s(ln(S_{t-2})) + \\epsilon$", Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F="", p.value="", AIC=round(AIC(get(mod)), digits=2), stringsAsFactors=FALSE)
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="II: $ln(N_t) = M1 + s(V_t)$", 
                Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="III: $ln(N_t) = M1 + s(V_t) + \\beta W_{t-1}$", Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)

m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=dat)
m2 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov1, sp=0.6), data=dat)
a=anova(m1,m2, test="F")

i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(Model="II: $ln(N_t) = M1 + s(W_{t-1})$", Residual.df=round(a[["Resid. Df"]][i],digits=1), Residual.dev=round(a[["Resid. Dev"]][i],digits=2), F=round(a$F[i],digits=2), p.value=round(a[["Pr(>F)"]][i], digits=3), AIC=round(AIC(get(mod)), digits=2))
tmp2=data.frame(Model=paste("\\kern 3em($R^2 adj$ = ",100*round(aa$r.sq, digits=2), "$\\%$, Var($\\epsilon$) = ", round(get(mod)$sig2, digits=2),")", sep=""), Residual.df="", Residual.dev="", F="", p.value ="", AIC="")
seltable=rbind(seltable,tmp1,tmp2)
```


```{r print-table3, echo=FALSE}
colnames(seltable)=c("Model", "Residual df", "Residual deviance", "F", "p value", "AIC")
if(isLatex) colnames(seltable)=c("Model", "\\shortstack{Residual\\\\df}", "\\shortstack{Residual\\\\deviance}", "F", "\\shortstack{p\\\\value}", "AIC")

thecap=paste("Top covariates for the $S_t$ (Jul-Sep catch) and $N_t$ (Oct-Jun catch) models. The models are nested; the roman numeral indicates the level of nestedness. Models at levels II and higher are shown with the component that is added to the base level model (M0 or M1) at top.  The full set of covariate models tested are given in Appendix B. The fitted versus observed catches from the covariate models are shown in Figure ", ref("fig:fitted"), ".", sep="")
fullcap=paste("Table ", ref("tab:covariate-models"), ". ", thecap, sep="")
kable(seltable, align="lccccc", caption=fullcap, escape=FALSE)
```