---
title: Use of satellite data for understanding and predicting oil sardine (*Sardinella longiceps*) catch variability along the southwest coast of India
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = 'setup.Rmd'}
```

```{r cov-effects, echo=FALSE,fig.cap=paste("Figure",  ref("fig:cov-effects")), fig.width=8,fig.height=6,message=FALSE,warning=FALSE}
oldpar=par(mfrow=c(2,2), mar=c(4,5,2,0))
dat=dat.spawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.4.mon1to1.1")
covtits =  c("Aug-Oct SST current season", "Aug-Oct SST prior season")
dat$cov0=dat[[covnames[1]]]
dat$cov1=dat[[covnames[2]]]
m1 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov1, sp=0.6), data=dat)
plot(m1, select=2, xlab="coastal SST in Aug-Oct cur year", ylab="Effect")
legend("topright","A", bty="n")
legend("topleft","Model 1", bty="n")
abline(h=0, col="grey")
plot(m2, select=2, xlab="coastal SST in Aug-Oct prior season", ylab="Effect")
legend("topright","B", bty="n")
abline(h=0, col="grey")
legend("topleft","Model 1", bty="n")

dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon10to11.1")
covnames=c("SST.UPW.4.mon7to9.0", "SST.UPW.4.mon10to11.1")
covnames=c("SST.UPW.4.mon7to9.0", "SST.UPW.4.mon7to9.1")
covtits =  c("Jul-Sep SST current season", "Oct-Dec UPW prior season")
dat$cov0=dat[[covnames[1]]]
dat$cov1=dat[[covnames[2]]]
m0 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=dat)
m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov1, sp=0.6), data=dat)
m3 = gam(nspawners0 ~ nspawners1 +  s(cov0, sp=0.6), data=dat)
m4 = gam(catchq4.0 ~ s(nspawners1, sp=0.6) +  s(cov0, sp=0.6), data=dat)
m1 = gam(catchq4.0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(catchq4.0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov1, sp=0.6), data=dat)
plot(m1, select=3, xlab="coastal SST in spawning months", ylab="Effect")
legend("topright","C", bty="n")
legend("topleft","Model 2", bty="n")
abline(h=0, col="grey")
plot(m2, select=3, xlab="Oct-Dec upwelling index in prior season", ylab="Effect")
legend("topright","D", bty="n")
legend("topleft","Model 2", bty="n")
abline(h=0, col="grey")
abline(v=0, col="blue")
text(0,-2,"upwelling\ncoast colder\nthan offshore",pos=4)
text(0,-2,"coast warmer\nthan offshore",pos=2)
par(oldpar)
```

```{r cov-effects, echo=FALSE,fig.cap=paste("Figure",  ref("fig:cov-effects")), fig.width=8,fig.height=6,message=FALSE,warning=FALSE}
oldpar=par(mfrow=c(1,1), mar=c(4,5,2,0))
dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to12.1")
covnames=c("SST.UPW.4.mon11to12.1")
covnames=c("SST.4.mon11to12.1")
covtits =  c("Upwelling direction Nov-Dec prior year")
dat$cov0=dat[[covnames[1]]]
m0 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=dat)
m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
plot(m1, select=3, xlab=covtits, ylab="Effect")
abline(h=0, col="grey")
abline(v=0, col="blue")
par(oldpar)
```

```{r cov-effects, echo=FALSE,fig.cap=paste("Figure",  ref("fig:cov-effects")), fig.width=8,fig.height=6,message=FALSE,warning=FALSE}
oldpar=par(mfrow=c(1,1), mar=c(4,5,2,0))
dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.UPW.4.mon6to7.1")
covtits =  c("June-July upwelling prior year")
dat$cov0=dat[[covnames[1]]]
m0 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=dat)
m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
plot(m1, select=3, xlab=covtits, ylab="Effect")
abline(h=0, col="grey")
abline(v=0, col="blue")
par(oldpar)
```

```{r fitted, echo=FALSE,fig.cap=paste("Figure",  ref("fig:fitted")), fig.width=8,fig.height=8,message=FALSE,warning=FALSE}
jig=.3
oldpar=par(mfrow=c(2,2), mar=c(4,6,1,0))
dat=dat.spawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon1to3.1")
covtits =  c("Jul-Sep SST current season", "Jan-Mar UPW prior season")
dat$cov0=dat[["SST.4.mon7to9.0"]]
dat$cov1=dat[["SST.UPW.4.mon1to3.1"]]
m0 = gam(spawners0 ~ s(nspawners1, sp=0.6), data=dat)
m1 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov1, sp=0.6), data=dat)
m3 = gam(spawners0 ~ s(nspawners1, sp=0.6) + s(cov1, sp=0.6) + s(cov0, sp=0.6), data=dat)
# m2$model=exp(m2$model); m2$fitted.values=exp(m2$fitted.values)
# m0$model=exp(m0$model); m0$fitted.values=exp(m0$fitted.values)
xmin=min(m2$model[,"spawners0"],m2$fitted.values)
xmax=jig+max(m2$model[,"spawners0"],m2$fitted.values)
plot(m0$model[,"spawners0"],m0$fitted.values, xlim=c(xmin,xmax), ylim=c(xmin,xmax),
     xlab="Log catch in spawning months", ylab="Predicted log catch\nwithout upwelling")
lines(c(xmin,xmax),c(xmin,xmax-jig))
legend("topleft",paste("R2 =",round(100*summary(m0)$r.sq,digits=1)), bty="n")
legend("topright","A", bty="n")

plot(m2$model[,"spawners0"],m2$fitted.values, xlim=c(xmin,xmax), ylim=c(xmin,xmax),
     xlab="Log catch in spawning months", ylab="Predicted log catch\nwith upwelling")
lines(c(xmin,xmax-jig),c(xmin,xmax-jig))
legend("topleft",paste("R2 =",round(100*summary(m2)$r.sq,digits=1)), bty="n")
legend("topright","B", bty="n")

dat=dat.nonspawners
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
covnames=c("SST.4.mon7to9.0", "SST.UPW.4.mon10to12.1")
covtits =  c("Jul-Sep SST current season", "Nov-Dec UPW prior season")
dat$cov0=dat[["SST.4.mon7to9.0"]]
dat$cov1=dat[["SST.UPW.4.mon10to12.1"]]
m0 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6), data=dat)
m1 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6), data=dat)
m2 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov1, sp=0.6), data=dat)
m3 = gam(nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6) + s(cov0, sp=0.6) + cov1, data=dat)
# m2$model=exp(m2$model); m2$fitted.values=exp(m2$fitted.values)
# m0$model=exp(m0$model); m0$fitted.values=exp(m0$fitted.values)
xmin=min(m0$model[,"nspawners0"],m0$fitted.values,m3$fitted.values)
xmax=jig+max(m0$model[,"nspawners0"],m0$fitted.values,m3$fitted.values)
plot(m0$model[,"nspawners0"],m0$fitted.values, xlim=c(xmin,xmax), ylim=c(xmin,xmax),
     xlab="Log catch in non-spawning months", ylab="Predicted log catch\nwithout covariates")
lines(c(xmin,xmax),c(xmin,xmax-jig))
legend("topleft",paste("R2 =",round(100*summary(m0)$r.sq,digits=1)), bty="n")
legend("topright","C", bty="n")

plot(m3$model[,"nspawners0"],m3$fitted.values, xlim=c(xmin,xmax), ylim=c(xmin,xmax),
     xlab="Log catch in non-spawning months", ylab="Predicted log catch\nwith covariates")
lines(c(xmin,xmax-jig),c(xmin,xmax-jig))
legend("topleft",paste("R2 =",round(100*summary(m3)$r.sq,digits=1)), bty="n")
legend("topright","D", bty="n")

par(oldpar)
```