---
title: "Updates"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# April 2020

### April 14-16, 2020

Done

* Finished the appendices
* Finished cleaning up supporting material
* First edit of Table 1
* Editted Table 2
* Added acknowledgements and keywords and authors

To do

* Edit discussion and conclusion
* R programming language (R Development Core Team, 2019)
* Check ref to Figure 5
* Look for ref for why precip over land might be bad
* Address remaining editor comments in Word doc
* ?? Test of autocorrelation of residuals and normality to appendix
* Compare edited text to old text
* Check that data supplement has all the data

### April 11, 2020

Done

* Made the appendix table for nonspawners. Finished appendices.
* Removed Chl Jan-Mar, added H1 labels to Chl.
* Nothing else on to do list finished

To do

* ~~Edit Table 2 per changes in appendices~~
* R programming language (R Development Core Team, 2019)

### April 10, 2020

Done

* Made the appendix table for spawners. Should be easy now to do non-spawners

To do

* ~~Move some of the main covariate tables to Appendices which will appear with the text~~
* ~~Fix the refs to supplement tables in main text~~
* Editor says cut this. ~~Add refs to each hypothesis in the results~~
* ~~Discuss the land precipitation results briefly or cut the land precipitation data.~~

* Test of autocorrelation of residuals and normality to appendix
* Revamp discussion per editors comments
* Compare edited text to old text

### April 9, 2020 Done

* Fixed the figures
* Changed appendices to supplement and cut some unneeded appendices
* Fixed Chl data to nearshore


# February-April 2020

Working on getting into final form. Revision after revision.

# October-November 2019

Worked on revamping the analyses based on the comments from the Kochi meeting.

# September, 2019

Meeting in Kochi. Got comments on paper. Revamped the hypotheses.

# June-August, 2019

I spent the summer revamping and clarifying the hypotheses to test (per comments from literature, Smitha, and Mark & Dave). I then redid all the analyses focusing on the hypotheses and then needed to rewrite results, tables, figures, and discussion.

### Other stuff

* simplified the table structure a bit
* wrote the discussion
* rewrote introduction
* lots of work on cleaning up references

### To do

* Edit for specific journal
* ~~Write abstract~~
* Do I need a detailed version of the hypotheses table with references? in the appendix? Refs are currently scattered in introduction.
* Test of autocorrelation of residuals and normality to appendix
* ~~Need to do influence analysis via cross-validation (LOO).  1994 catch is influential and outlier.~~
* ~~Cut the cartoon of sardine life-cycle? Or need to improve the quality of the figure.~~
* Need to discuss the land precipitation results briefly or cut the land precipitation data. 
* Discuss the CHL results more?

### Things that would be interesting but not necessary before submitting

* cross-validation test of the catch models? Maybe not.
* Look at the paper that found correlation with MEI and annual landings. Maybe use MEI instead of ONI? or use ONI_t? That's a question for the others. What is the best ENSO metric and why? Supraba et al 2016: Climate influence on oil sardine and Indian mackerel in southeastern Arabian Sea
* ONI can be tested with full data set.  Add that.
* Might be interesting do windowing and see how SST average correlates for different windows.
* Because SST average was good, try average over larger region.  If that works, then ICOADS SST might work.

# May 10-21, 2019

Did the SST transect studies to look for better/other ways to characterize the SST gradients both temporally and spatially. This work is summarized here.

http://rpubs.com/eeholmes/SSTKerala

Not clear how/whether to use this for Sardine Paper 2. Leave for Sardine Paper 3 (upwelling dynamics).

Maybe redo with SST seasonal anomaly like in Boyer et al 2001.

# May 8, 2019

Updated the SardineForecast package with the `tidelevel` dataset and updated the documentation under `?tidelevel`. Updated Sardine.bib with the references.

I did some cursory looking at the tide level anomalies against the catches. No obvious relationships. Studies have found a relationship between mean sea level and SOI but that relationship does not seem to hold for the whole 1939-2018 time series. It seems to hold for some shorter periods however.

Next: Re look at Dave's suggestions for how to use sea level as a covariate. Not clear to me how to use it. Also there is a strong seasonal cycle in sea level. Should one use one part of this cycle, like Sept, or just use the mean annual level?

Status: Not clear how to use tide level and no obvious relationship. I can add this in as a hypothesis but need more direction on what *exactly* to use. I don't want to go on a fishing expediction with tide-level.

# May 7, 2019

Merged the 3 tide gauge data sets. Then 

* filled in any NAs using exponential smoothing
* created annual means
* created anomalies by removing linear trend and mean level

Next, need to update the citation and man file for the data. Create some figures for the appendices.

# May 6, 2019

Working on downloading tide gauge data. The different data sets have different missing values, so I downloaded from 3 sources. Big gap 2008-2009. Tide gauge must have been broken.

* raw minute data from 2011-present http://www.ioc-sealevelmonitoring.org/station.php
* raw daily data from 2011 http://uhslc.soest.hawaii.edu/data/?fd#uh174
* monthly average data scaled to mean tide level https://www.psmsl.org/data/obtaining/stations/438.php

# May 3, 2019

Dave suggested using SSH as a covariate however remote sensing data on SSH is only available into 1990s so not very useful.  Tide height at Cochin is available for full catch data set. Normally tide height data is corrected for inverse barometric pressure but Srinivas and Kumar (2006) looked at the difference between tide height at Cochi and the corrected sea level and found not much difference, so I'll the uncorrected tide level. Srivivas and Kumar (2006) and Srinivas et al (2005) found a relationship between sea level and ENSO phenomena.

K. Srinivas, P.K. Dinesh Kumar. 2006. Atmospheric forcing on the seasonal variability of sea level at Cochin, southwest coast of India, Continental Shelf Research, Volume 26, Issue 10, pp1113-1133.

K. Srinivas, P.K. Dinesh Kumar, C. Revichandran. ENSO signature in the sea level along the coastline of the Indian subcontinent. Indian Journal of Marine Sciences, 34 (2005), pp. 225-236
 
# May 2, 2019

Collecting background references for the introduction and discussion on climate forcing for small pelagics and ocean variables and sardine catch.

Tommasi et al. 2017. Improved management of small pelagic fisheries through seasonal climate prediction. Ecological Applications 27:378-388.
