m0=gam(spawners0~1, data=df2)
m1=gam(spawners0~s(spawners1, sp=0.6), data=df2)
m2=gam(spawners0~s(spawners1, sp=0.6)+s(spawners2, sp=0.6), data=df2)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), SardineForecast:::AICcgam(m2))

m0=gam(spawners0~1, data=df2)
m1=gam(spawners0~s(nspawners1, sp=0.6), data=df2)
m2=gam(spawners0~s(nspawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df2)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), SardineForecast:::AICcgam(m2))

m0=gam(spawners0~1, data=df)
m1=gam(spawners0~s(nspawners1, sp=0.6), data=df)
m2=gam(spawners0~s(nspawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), SardineForecast:::AICcgam(m2))
c(AIC(m0), AIC(m1), AIC(m2))

m0=gam(spawners0~1, data=df)
m1=gam(spawners0~s(spawners1, sp=0.6), data=df)
m2=gam(spawners0~s(spawners1, sp=0.6)+s(spawners2, sp=0.6), data=df)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), SardineForecast:::AICcgam(m2))
c(AIC(m0), AIC(m1), AIC(m2))


m0=gam(nspawners0~1, data=df)
m1=gam(nspawners0~s(nspawners1, sp=0.6), data=df)
m2=gam(nspawners0~s(nspawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), SardineForecast:::AICcgam(m2))
c(AIC(m0), AIC(m1), AIC(m2))

df3 <- dforig
df3 <- subset(dat.nonspawners, !(Year%in%rmyr))
m0=gam(nspawners0 ~ nspawners1, data=df3)
m1=gam(nspawners0~s(nspawners1, sp=0.6), data=df3)
m2=gam(nspawners0~s(nspawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df3)
m3=gam(nspawners0~s(nspawners1, sp=0.6)+s(spawners2, sp=0.6), data=df3)
#m3=gam(nspawners0~nspawners1, data=df3)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), 
  SardineForecast:::AICcgam(m2), SardineForecast:::AICcgam(m3))
c(SardineForecast:::loogam(m0)$RMSE, SardineForecast:::loogam(m1)$RMSE, 
  SardineForecast:::loogam(m2)$RMSE, SardineForecast:::loogam(m3)$RMSE)
c(SardineForecast:::loogam(m0)$MdAE, SardineForecast:::loogam(m1)$MdAE, 
  SardineForecast:::loogam(m2)$MdAE, SardineForecast:::loogam(m3)$MdAE)
#c(AIC(m0), AIC(m1), AIC(m2), AIC(m3))
plot(df$nspawners0,df$nspawners1)
plot(m1$model$nspawners0, fitted(m1))

loof <- SardineForecast:::loogam(m0)
plot(loof$actual, ylim=c(9, 12.5))
lines(loof$pred)
loof <- SardineForecast:::loogam(m1)
lines(loof$pred, col="red")
loof <- SardineForecast:::loogam(m2)
lines(loof$pred, col="blue")
loof <- SardineForecast:::loogam(m3)
lines(loof$pred, col="green")

df3 <- subset(df, Year>1984)
m0=gam(spawners0~offset(spawners1), data=df3)
m1=gam(spawners0~s(spawners1, sp=0.6), data=df3)
m2=gam(spawners0~s(nspawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df3)
m3=gam(spawners0~s(nspawners1, sp=0.6)+s(spawners2, sp=0.6), data=df3)
m3=gam(spawners0~spawners1, data=df3)
c(SardineForecast:::AICcgam(m0), SardineForecast:::AICcgam(m1), 
  SardineForecast:::AICcgam(m2), SardineForecast:::AICcgam(m3))
summary(m3)
#c(AIC(m0), AIC(m1), AIC(m2), AIC(m3))
plot(df$spawners0,df$spawners1)
plot(m3$model$spawners0, fitted(m3))

df3 <- dforig
df3 <- subset(df3, Year>1980 & Year<2019 )
#df3 <- subset(df3, !(Year%in%bad))
m0=gam(nspawners0 ~ nspawners1, data=df3)
m1=gam(nspawners0~s(nspawners1, sp=0.6), data=df3)
m2=gam(nspawners0~s(nspawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df3)
m3=gam(nspawners0~s(nspawners1, sp=0.6)+s(spawners2, sp=0.6), data=df3)
par(mfrow=c(2,1))
plot(df3$Year, df3$nspawners0, pch=16)
#lines(df3$Year, fitted(m0))
lines(df3$Year, fitted(m1), col="red")
lines(df3$Year, fitted(m2), col="blue")
lines(df3$Year, fitted(m3), col="green")

loof <- SardineForecast:::loogam(m0)
plot(loof$actual, ylim=c(6, 12.5))
lines(loof$pred)
loof <- SardineForecast:::loogam(m1)
lines(loof$pred, col="red")
loof <- SardineForecast:::loogam(m2)
lines(loof$pred, col="blue")
loof <- SardineForecast:::loogam(m3)
lines(loof$pred, col="green")


df3 <- dforig
df3 <- subset(df3, Year>1970 & Year<2001 )
#df3 <- subset(df3, !(Year%in%bad))
m0=lm(spawners0 ~ -1+offset(spawners1), data=df3)
m1=gam(spawners0~s(spawners1, sp=0.6), data=df3)
m2=gam(spawners0~s(spawners1, sp=0.6)+s(nspawners2, sp=0.6), data=df3)
m3=gam(spawners0~s(spawners1, sp=0.6)+s(spawners2, sp=0.6), data=df3)
plot(df3$Year, df3$spawners0, pch=16)
#lines(fitted(m0))
lines(df3$Year, fitted(m1), col="red")
lines(df3$Year, fitted(m2), col="blue")
lines(df3$Year, fitted(m3), col="green")